server:
  context-path: /backend
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  profiles:
     active: dev

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sybr?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123@abcd
#      url: jdbc:mysql://120.25.216.91:3306/sybr?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: Khbfch050117@123

  mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.sybr.backend.entity

logging:
  level:
    com.sybr.backend.dao: debug


