spring:
  profiles:
     active: dev

  mvc:
      view:
        prefix: /
        suffix: .jsp

server:
  #context-path: /backend
  port: 8888
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

